export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO'
export const OBTENER_TURNOS = 'OOBTENER_TURNOS'
export const AGREGAR_TURNO = 'AGREGAR_TURNO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const ELIMINAR_TURNO = 'ELIMINAR_TURNO';

export const EDITAR_TURNO='EDITAR_TURNO'
export const EDITAR_TURNO_EXITO='EDITAR_TURNO_EXITO'
export const EDITAR_TURNO_ERROR='EDITAR_TURNO_ERROR'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const ENVIO_CORREO = 'ENVIO_CORREO';

export const NUEVO_DOCTOR = 'NUEVO_DOCTOR';
export const OBTENER_DOCTORES = 'OBTENER_DOCTORES';


/**/


//export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
//export const TURNO_ERROR = 'TURNO_ERROR';




